# **Data Gathering**

Link Kaggle Dataset

*   Dataset 2020: https://www.kaggle.com/datasets/andrewmvd/data-analyst-jobs
*   Dataset 2022 & 2023: https://www.kaggle.com/datasets/simonebaldi/data-analyst-jobs-posting
*   Dataset 2024: https://www.kaggle.com/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024
*   Dataset 2025:https://www.kaggle.com/datasets/joykimaiyo18/linkedin-data-jobs-dataset

In [476]:
import pandas as pd
import numpy as np
import re
from tqdm.auto import tqdm

import ast
from matplotlib_venn import venn2
import matplotlib.pyplot as plt
import plotly.express as px

**Dataset 2020**

In [477]:
url='https://docs.google.com/spreadsheets/d/e/2PACX-1vTbzY0oW8XQ6TT9WWqQbfSatibBLcxayarERA513r2E8iiGGMixx44zjU6hi0Mlqec3Fgt16usLtrF-/pub?gid=1105378740&single=true&output=csv'
df_data20 = pd.read_csv(url)
df_data20.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,TRUE
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,TRUE

In [478]:
df_data20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5631 entries, 0 to 5630
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5631 non-null   object
 1   Salary Estimate    5631 non-null   object
 2   Job Description    5631 non-null   object
 3   Rating             5631 non-null   float64
 4   Company Name       5629 non-null   object
 5   Location           5631 non-null   object
 6   Headquarters       5631 non-null   object
 7   Size               5631 non-null   object
 8   Founded            5631 non-null   int64
 9   Type of ownership  5631 non-null   object
 10  Industry           5631 non-null   object
 11  Sector             5631 non-null   object
 12  Revenue            5631 non-null   object
 13  Competitors        5631 non-null   object
 14  Easy Apply         5631 non-null   object
dtypes: float64(1), int64(1), object(13)
memory usage: 660.0+ KB

In [479]:
df_data20 = df_data20.rename(columns={
    'Job Title' : 'posisi',
    'Job Description': 'deskripsi',
    'Company Name' : 'perusahaan',
    'Location' : 'lokasi'
})

df_data20 = df_data20[['posisi', 'deskripsi', 'perusahaan', 'lokasi']]
df_data20["tahun"] = 2020
df_data20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5631 entries, 0 to 5630
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      5631 non-null   object
 1   deskripsi   5631 non-null   object
 2   perusahaan  5629 non-null   object
 3   lokasi      5631 non-null   object
 4   tahun       5631 non-null   int64
dtypes: int64(1), object(4)
memory usage: 220.1+ KB

In [480]:
df_data20.duplicated().sum()

np.int64(0)

In [481]:
df_data20.isna().sum()

posisi        0
deskripsi     0
perusahaan    2
lokasi        0
tahun         0
dtype: int64

In [482]:
df_data20 = df_data20.dropna()
df_data20.isna().sum()
df_data20.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5629 entries, 0 to 5630
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      5629 non-null   object
 1   deskripsi   5629 non-null   object
 2   perusahaan  5629 non-null   object
 3   lokasi      5629 non-null   object
 4   tahun       5629 non-null   int64
dtypes: int64(1), object(4)
memory usage: 263.9+ KB

In [483]:
keywords = 'Data Analyst'
df_filtered20 = df_data20[df_data20['posisi'].str.contains(keywords, case=False, na=False)].copy()

print(f"Sisa data: {len(df_filtered20)} baris")
df_filtered20['posisi'].value_counts()

Sisa data: 4119 baris

posisi
Data Analyst                                            982
Senior Data Analyst                                     184
Junior Data Analyst                                      90
Business Data Analyst                                    57
Data Analyst Junior                                      55
                                                       ...
Sr. Data Analyst/ Data Architect                          1
Senior Data Analyst (Remote, USA, Full-Time)              1
Data Analyst -1+ year Contract - NYC                      1
Analyst/Associate Global Markets Credit Data Analyst      1
Data Analyst (Games)                                      1
Name: count, Length: 1709, dtype: int64

In [484]:
df_filtered20.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4119 entries, 0 to 5630
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      4119 non-null   object
 1   deskripsi   4119 non-null   object
 2   perusahaan  4119 non-null   object
 3   lokasi      4119 non-null   object
 4   tahun       4119 non-null   int64
dtypes: int64(1), object(4)
memory usage: 193.1+ KB

**Dataset 2022**

In [485]:
url='https://docs.google.com/spreadsheets/d/e/2PACX-1vRS5CW5AXiCwn6IWizrNXgc5IZcgNI9LeEdv2E3X-RugalXPSRlT_kvgo-Gk65YskrJl8N9ZMa2_lCR/pub?gid=1321416123&single=true&output=csv'
df_data22 = pd.read_csv(url)
df_data22.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,...,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,18094,471,Data Analyst II,EDWARD JONES,"Chamois, MO",via WDHN Jobs,"At Edward Jones, we help clients achieve their...","['1 hour ago', '76,798–130,764 a year', 'Full-...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSUkiLCJodG...,NaN,...,NaN,76798–130764,a year,103781.0,76798.0,130764.0,NaN,103781.0,103781.0,"['spss', 'r', 'sql', 'python', 'snowflake', 's..."
1,18095,472,Senior Performance Marketing (Data Analyst),EDWARD JONES,"Nixa, MO",via WTRF Jobs,"At Edward Jones, we help clients achieve their...","['1 hour ago', '90,628–154,313 a year', 'Full-...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgUGVyZm9ybWFuY2UgTW...,NaN,...,NaN,90628–154313,a year,122470.5,90628.0,154313.0,NaN,122470.5,122470.5,"['nosql', 'spss', 'vba', 'tableau', 'r', 'pl/s..."
2,18097,474,Intern: Financial Data Analyst,EquipmentShare,"Columbia, MO",via Startup Jobs,EquipmentShare is Hiring an Financial Data Ana...,"['2 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJJbnRlcm46IEZpbmFuY2lhbCBEYX...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['spss', 'r', 'sql', 'python', 'sas', 'excel']"
3,18133,510,"Senior Data Analyst, Oracle CX Marketing",Oracle,"Oklahoma City, OK",via My Valley Jobs Today,Job Description\n\nOracle CX Marketing has an ...,"['2 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0LC...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['r', 'sql', 'python', 'go', 'excel', 'powerpo..."
4,18141,518,Data Analyst IV (Utilization Mgmt),Centene Corporation,"Oklahoma City, OK",via Jobs For Stevenage Fans,You could be the one who changes everything fo...,"['2 hours ago', 'Full-time', 'Health insurance...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSVYgKFV0aW...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['sql', 'microstrategy', 'ssis', 'excel', 'pow..."

In [486]:
df_data22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1325 entries, 0 to 1324
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1325 non-null   int64
 1   index                1325 non-null   int64
 2   title                1325 non-null   object
 3   company_name         1325 non-null   object
 4   location             1325 non-null   object
 5   via                  1325 non-null   object
 6   description          1325 non-null   object
 7   extensions           1325 non-null   object
 8   job_id               1325 non-null   object
 9   thumbnail            586 non-null    object
 10  posted_at            1325 non-null   object
 11  schedule_type        1322 non-null   object
 12  work_from_home       0 non-null      float64
 13  salary               104 non-null    object
 14  search_term          1325 non-null   object
 15  date_time            1325 non-null   object
 16  search_location      1325 non-null   object
 17  commute_time         0 non-null      float64
 18  salary_pay           104 non-null    object
 19  salary_rate          104 non-null    object
 20  salary_avg           104 non-null    float64
 21  salary_min           91 non-null     float64
 22  salary_max           91 non-null     float64
 23  salary_hourly        14 non-null     float64
 24  salary_yearly        90 non-null     float64
 25  salary_standardized  104 non-null    float64
 26  description_tokens   1325 non-null   object
dtypes: float64(8), int64(2), object(17)
memory usage: 279.6+ KB

In [487]:
df_data22 = df_data22.rename(columns={
    'title' : 'posisi',
    'description': 'deskripsi',
    'company_name' : 'perusahaan',
    'location' : 'lokasi'
})

df_data22 = df_data22[['posisi', 'deskripsi', 'perusahaan', 'lokasi']]
df_data22["tahun"] = 2022
df_data22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1325 entries, 0 to 1324
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1325 non-null   object
 1   deskripsi   1325 non-null   object
 2   perusahaan  1325 non-null   object
 3   lokasi      1325 non-null   object
 4   tahun       1325 non-null   int64
dtypes: int64(1), object(4)
memory usage: 51.9+ KB

In [488]:
df_data22.duplicated().sum()

np.int64(243)

In [489]:
df_data22 = df_data22.drop_duplicates()
df_data22.duplicated().sum()

np.int64(0)

In [490]:
keywords = 'Data Analyst'
df_filtered22 = df_data22[df_data22['posisi'].str.contains(keywords, case=False, na=False)].copy()

print(f"Sisa data: {len(df_filtered22)} baris")
df_filtered22['posisi'].value_counts()

Sisa data: 1082 baris

posisi
Data Analyst II                                          119
Data Analyst                                             102
Lead Data Analyst                                         88
Senior Performance Marketing (Data Analyst)               53
Senior Data Analyst                                       49
                                                        ...
Senior Data Analyst - CXT Cloud Operations                 1
Data Analyst Product MP                                    1
Lead Business Data Analyst - Global Delivery Services      1
Neuroimaging Data Analyst                                  1
SAP S4 Hana Master Data Analyst                            1
Name: count, Length: 302, dtype: int64

In [491]:
df_filtered22.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1082 entries, 0 to 1324
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1082 non-null   object
 1   deskripsi   1082 non-null   object
 2   perusahaan  1082 non-null   object
 3   lokasi      1082 non-null   object
 4   tahun       1082 non-null   int64
dtypes: int64(1), object(4)
memory usage: 50.7+ KB

**Dataset 2023**

In [492]:
url='https://docs.google.com/spreadsheets/d/e/2PACX-1vQ0caIZChMuBEwM9kFslIhsYRdwNnh4_2PgEBEsAxWUBeG4UW7_rBz1Vb9jRTla82OPcXH7kgH37gnB/pub?gid=914463674&single=true&output=csv'
df_data23 = pd.read_csv(url)
df_data23.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,...,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,18085,462,Senior Business Data Analyst,U.S. Bank,"Oklahoma City, OK",via My Stateline Jobs,"At U.S. Bank, we're passionate about helping c...","['1 hour ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJTZW5pb3IgQnVzaW5lc3MgRGF0YS...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
1,18129,506,Data Analyst,Talent Acquisition Concepts,"Jefferson City, MO",via WayUp,[]\n\nARE YOU LOOKING FOR A CHALLENGE? Looking...,"['2 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['word', 'spreadsheet', 'spreadsheet']"
2,18132,509,Senior Data Analyst,Interas Labs,"Dearing, KS",via SonicJobs,"Hi Folks,\n\nHope you are doing well...\n\nThi...","['2 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['python', 'spss', 'sql', 'sas', 'excel', 'tab..."
3,18150,527,Data Analyst II (Healthcare Analytics),Corporate,"Jefferson City, MO",via WDHN Jobs,You could be the one who changes everything fo...,"['2 hours ago', 'Full-time', 'Health insurance...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSUkgKEhlYW...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['python', 'sql', 'excel', 'power_bi']"
4,18152,529,Data Analyst I,NelNEt,"Oklahoma City, OK",via My Stateline Jobs,Nelnet is a diversified and innovative company...,"['2 hours ago', 'Full-time', 'Health insurance...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgSSIsImh0aW...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['t-sql', 'dax', 'sql', 'postgresql', 'python'..."

In [493]:
df_data23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2527 entries, 0 to 2526
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           2527 non-null   int64
 1   index                2527 non-null   int64
 2   title                2527 non-null   object
 3   company_name         2527 non-null   object
 4   location             2527 non-null   object
 5   via                  2527 non-null   object
 6   description          2527 non-null   object
 7   extensions           2527 non-null   object
 8   job_id               2527 non-null   object
 9   thumbnail            1000 non-null   object
 10  posted_at            2527 non-null   object
 11  schedule_type        2491 non-null   object
 12  work_from_home       0 non-null      float64
 13  salary               443 non-null    object
 14  search_term          2527 non-null   object
 15  date_time            2527 non-null   object
 16  search_location      2527 non-null   object
 17  commute_time         0 non-null      float64
 18  salary_pay           443 non-null    object
 19  salary_rate          443 non-null    object
 20  salary_avg           443 non-null    float64
 21  salary_min           415 non-null    float64
 22  salary_max           415 non-null    float64
 23  salary_hourly        32 non-null     float64
 24  salary_yearly        411 non-null    float64
 25  salary_standardized  443 non-null    float64
 26  description_tokens   2527 non-null   object
dtypes: float64(8), int64(2), object(17)
memory usage: 533.2+ KB

In [494]:
df_data23 = df_data23.rename(columns={
    'title' : 'posisi',
    'description': 'deskripsi',
    'company_name' : 'perusahaan',
    'location' : 'lokasi'
})

df_data23 = df_data23[['posisi', 'deskripsi', 'perusahaan', 'lokasi']]
df_data23["tahun"] = 2023
df_data23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2527 entries, 0 to 2526
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      2527 non-null   object
 1   deskripsi   2527 non-null   object
 2   perusahaan  2527 non-null   object
 3   lokasi      2527 non-null   object
 4   tahun       2527 non-null   int64
dtypes: int64(1), object(4)
memory usage: 98.8+ KB

In [495]:
df_data23.duplicated().sum()

np.int64(760)

In [496]:
df_data23 = df_data23.drop_duplicates()
df_data23.duplicated().sum()
df_data23.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1767 entries, 0 to 2525
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1767 non-null   object
 1   deskripsi   1767 non-null   object
 2   perusahaan  1767 non-null   object
 3   lokasi      1767 non-null   object
 4   tahun       1767 non-null   int64
dtypes: int64(1), object(4)
memory usage: 82.8+ KB

In [497]:
keywords = 'Data Analyst'
df_filtered23 = df_data23[df_data23['posisi'].str.contains(keywords, case=False, na=False)].copy()

print(f"Sisa data: {len(df_filtered23)} baris")
df_filtered23['posisi'].value_counts()

Sisa data: 1767 baris

posisi
Data Analyst                                    262
Senior Data Analyst                              86
Lead Data Analyst                                78
Data Analyst II                                  60
Sr. Data Analyst, Marketing Operations           42
                                               ...
Lead Master Data Analyst (Springdale, AR)         1
Benefits Data Analyst                             1
Data Analyst, Blockchain Experience [Remote]      1
Data Analyst - Business Intelligence              1
COOP - Senior Data Analyst                        1
Name: count, Length: 422, dtype: int64

In [498]:
df_filtered23.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1767 entries, 0 to 2525
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1767 non-null   object
 1   deskripsi   1767 non-null   object
 2   perusahaan  1767 non-null   object
 3   lokasi      1767 non-null   object
 4   tahun       1767 non-null   int64
dtypes: int64(1), object(4)
memory usage: 82.8+ KB

**Dataset 2024**

In [499]:
url='https://docs.google.com/spreadsheets/d/e/2PACX-1vQiOe-xZSFyLw1VMbpAfkJs67kr7vMYLeib5PprK0D5j9YdjSruq9xh3aH6D-_5hJjlta9Qf0gVjLx0/pub?gid=1217709653&single=true&output=csv'
df_data24 = pd.read_csv(url)
df_data24.head()

,job_link,last_processed_time,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type,job_summary
0,https://www.linkedin.com/jobs/view/senior-fina...,2024-01-21 07:14:50.991803+00,t,t,f,Senior Financial Data Analyst,The Walt Disney Company,"Lake Buena Vista, FL",2024-01-15,Avondale,United States,Budget Officer,Mid senior,Onsite,Enterprise Technology/Telecom is looking for s...
1,https://www.linkedin.com/jobs/view/sr-workforc...,2024-01-21 07:15:01.601597+00,t,t,f,Sr. Workforce Management Data Analyst,"Wisemen Multimedia, LLC","Atlanta, GA",2024-01-13,Stockbridge,United States,Management Analyst,Mid senior,Onsite,Sr. Workforce Management Data Analyst - Alvari...
2,https://www.linkedin.com/jobs/view/contractor-...,2024-01-21 07:16:15.96147+00,t,t,f,Contractor - Epic Clarity Data Analyst - Reven...,Deloitte,"Mississippi, United States",2024-01-14,Magnolia,United States,Data Entry Clerk,Mid senior,Onsite,Position Summary\nContractor - Remote\nWork yo...
3,https://www.linkedin.com/jobs/view/vcp-design-...,2024-01-21 08:02:01.538039+00,t,t,f,VCP Design to Value Project Manager and Data A...,GE HealthCare,"Waukesha, WI",2024-01-14,Waterford,United States,Data Entry Clerk,Mid senior,Onsite,Job Description Summary\nAs a Sourcing Product...
4,https://www.linkedin.com/jobs/view/contractor-...,2024-01-21 08:17:36.039858+00,t,t,f,Contractor - Epic Clarity Data Analyst - Reven...,Deloitte,"Georgia, United States",2024-01-14,Macon,United States,Tumor Registrar,Mid senior,Onsite,Position Summary\nContractor - Remote\nWork yo...

In [500]:
df_data24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1581 entries, 0 to 1580
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_link             1581 non-null   object
 1   last_processed_time  1581 non-null   object
 2   got_summary          1581 non-null   object
 3   got_ner              1581 non-null   object
 4   is_being_worked      1581 non-null   object
 5   job_title            1581 non-null   object
 6   company              1581 non-null   object
 7   job_location         1581 non-null   object
 8   first_seen           1581 non-null   object
 9   search_city          1581 non-null   object
 10  search_country       1581 non-null   object
 11  search_position      1581 non-null   object
 12  job_level            1581 non-null   object
 13  job_type             1581 non-null   object
 14  job_summary          1545 non-null   object
dtypes: object(15)
memory usage: 185.4+ KB

In [501]:
df_data24 = df_data24.rename(columns={
    'job_title' : 'posisi',
    'job_summary': 'deskripsi',
    'company' : 'perusahaan',
    'job_location' : 'lokasi'
})

df_data24 = df_data24[['posisi', 'deskripsi', 'perusahaan', 'lokasi']]
df_data24["tahun"] = 2024
df_data24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1581 entries, 0 to 1580
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1581 non-null   object
 1   deskripsi   1545 non-null   object
 2   perusahaan  1581 non-null   object
 3   lokasi      1581 non-null   object
 4   tahun       1581 non-null   int64
dtypes: int64(1), object(4)
memory usage: 61.9+ KB

In [502]:
df_data24.duplicated().sum()

np.int64(28)

In [503]:
df_data24 = df_data24.drop_duplicates()
df_data24.duplicated().sum()
df_data24.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1553 entries, 0 to 1580
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1553 non-null   object
 1   deskripsi   1517 non-null   object
 2   perusahaan  1553 non-null   object
 3   lokasi      1553 non-null   object
 4   tahun       1553 non-null   int64
dtypes: int64(1), object(4)
memory usage: 72.8+ KB

In [504]:
df_data24.isna().sum()

posisi         0
deskripsi     36
perusahaan     0
lokasi         0
tahun          0
dtype: int64

In [505]:
df_data24 = df_data24.dropna()
df_data24.isna().sum()
df_data24.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1517 entries, 0 to 1580
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1517 non-null   object
 1   deskripsi   1517 non-null   object
 2   perusahaan  1517 non-null   object
 3   lokasi      1517 non-null   object
 4   tahun       1517 non-null   int64
dtypes: int64(1), object(4)
memory usage: 71.1+ KB

In [506]:
keywords = 'Data Analyst'
df_filtered24 = df_data24[df_data24['posisi'].str.contains(keywords, case=False, na=False)].copy()

print(f"Sisa data: {len(df_filtered24)} baris")
df_filtered24['posisi'].value_counts()

Sisa data: 1517 baris

posisi
Senior Data Analyst                                       118
Data Analyst                                               99
Contractor - Epic Clarity Data Analyst - Revenue Cycle     34
Contractor - Epic Clarity Data Analyst                     32
Lead Data Analyst                                          28
                                                         ...
Master Data Analyst (3 OPENINGS!)                           1
Principal Data Analyst - Enterprise & Sales                 1
Bioinformatician/Research Data Analyst                      1
Internal Audit Data Analyst Staff                           1
Data Analyst, Business Services                             1
Name: count, Length: 767, dtype: int64

In [507]:
df_filtered24.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1517 entries, 0 to 1580
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1517 non-null   object
 1   deskripsi   1517 non-null   object
 2   perusahaan  1517 non-null   object
 3   lokasi      1517 non-null   object
 4   tahun       1517 non-null   int64
dtypes: int64(1), object(4)
memory usage: 71.1+ KB

**Dataset 2025**

In [508]:
url='https://docs.google.com/spreadsheets/d/e/2PACX-1vRjCVJeyasHY0YdVIrK6MhwDv5vc2Cu2eHbu47ILhduY29V-m2xu-4W6BKQuW5ATDTIH_A2m-MGPYm8/pub?gid=342198788&single=true&output=csv'
df_data25 = pd.read_csv(url)
df_data25.head()

,id,title,company,location,link,source,date_posted,work_type,employment_type,description
0,1,Data Analyst,Meta,"New York, NY",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
1,2,Data Analyst,Meta,"San Francisco, CA",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
2,3,Data Analyst,Meta,"Los Angeles, CA",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
3,4,Data Analyst,Meta,"Washington, DC",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
4,5,Data Analyst II,Pinterest,"Chicago, IL",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-16,NaN,NaN,About Pinterest\n\nMillions of people around t...

In [509]:
df_data25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1048 non-null   int64
 1   title            1048 non-null   object
 2   company          1046 non-null   object
 3   location         1033 non-null   object
 4   link             1048 non-null   object
 5   source           959 non-null    object
 6   date_posted      1025 non-null   object
 7   work_type        0 non-null      float64
 8   employment_type  0 non-null      float64
 9   description      1044 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 82.0+ KB

In [510]:
df_data25 = df_data25.rename(columns={
    'description': 'deskripsi',
    'company' : 'perusahaan',
    'title' : 'posisi',
    'location' : 'lokasi'
})

df_data25 = df_data25[['posisi', 'deskripsi', 'perusahaan', 'lokasi']]
df_data25["tahun"] = 2025
df_data25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1048 non-null   object
 1   deskripsi   1044 non-null   object
 2   perusahaan  1046 non-null   object
 3   lokasi      1033 non-null   object
 4   tahun       1048 non-null   int64
dtypes: int64(1), object(4)
memory usage: 41.1+ KB

In [511]:
df_data25.duplicated().sum()

np.int64(7)

In [512]:
df_data25 = df_data25.drop_duplicates()
df_data25.duplicated().sum()
df_data25.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1041 entries, 0 to 1047
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1041 non-null   object
 1   deskripsi   1037 non-null   object
 2   perusahaan  1039 non-null   object
 3   lokasi      1026 non-null   object
 4   tahun       1041 non-null   int64
dtypes: int64(1), object(4)
memory usage: 48.8+ KB

In [513]:
df_data25.isna().sum()

posisi         0
deskripsi      4
perusahaan     2
lokasi        15
tahun          0
dtype: int64

In [514]:
df_data25 = df_data25.dropna()
df_data25.isna().sum()
df_data25.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020 entries, 0 to 1047
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      1020 non-null   object
 1   deskripsi   1020 non-null   object
 2   perusahaan  1020 non-null   object
 3   lokasi      1020 non-null   object
 4   tahun       1020 non-null   int64
dtypes: int64(1), object(4)
memory usage: 47.8+ KB

In [515]:
keywords = 'Data Analyst'
df_filtered25 = df_data25[df_data25['posisi'].str.contains(keywords, case=False, na=False)].copy()

print(f"Sisa data: {len(df_filtered25)} baris")
df_filtered25['posisi'].value_counts()

Sisa data: 272 baris

posisi
Data Analyst                       150
Senior Data Analyst                 11
Junior Data Analyst                  8
Business Data Analyst                7
Data Analyst II                      7
                                  ...
Research/Data Analyst, Senior        1
IIS Data Analyst II                  1
IT Data Analyst - System Access      1
Data Analyst II, SMART               1
Data Analyst V                       1
Name: count, Length: 77, dtype: int64

In [516]:
print(df_filtered25['lokasi'].value_counts())

lokasi
United States                         28
New York, NY                          23
London Area, United Kingdom           10
Bengaluru, Karnataka, India            8
San Francisco, CA                      7
                                      ..
Mountain View, CA                      1
Pittsburgh, PA, US                     1
Dubai, Dubai, United Arab Emirates     1
Edmonton, Alberta, Canada              1
Raleigh, NC                            1
Name: count, Length: 149, dtype: int64

In [517]:
kata_kunci = 'poland|canada|united kingdom|bulgaria|singapore|spain|ireland|indonesia|malaysia|germany|philippines|india|taiwan|United Arab Emirates|chile|argentina|mexico|france|Netherlands|brazil'

df_filtered25 = df_filtered25[~df_filtered25['lokasi'].str.contains(
    kata_kunci,
    na=False,
    case=False
)]

print("Jumlah baris:", len(df_filtered25))

Jumlah baris: 185

In [518]:
df_filtered25.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185 entries, 0 to 1016
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      185 non-null    object
 1   deskripsi   185 non-null    object
 2   perusahaan  185 non-null    object
 3   lokasi      185 non-null    object
 4   tahun       185 non-null    int64
dtypes: int64(1), object(4)
memory usage: 8.7+ KB

**Merge Dataset**

In [519]:
dataset = [df_filtered20, df_filtered22, df_filtered23, df_filtered24, df_filtered25]

df_merge = pd.concat(dataset, ignore_index=True)

print(f"Total baris setelah gabung: {len(df_merge)}")
df_merge.info()

Total baris setelah gabung: 8670
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8670 entries, 0 to 8669
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      8670 non-null   object
 1   deskripsi   8670 non-null   object
 2   perusahaan  8670 non-null   object
 3   lokasi      8670 non-null   object
 4   tahun       8670 non-null   int64
dtypes: int64(1), object(4)
memory usage: 338.8+ KB

In [520]:
df_merge.duplicated().sum()

np.int64(0)

In [521]:
df_merge = df_merge.drop_duplicates()
df_merge.duplicated().sum()
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8670 entries, 0 to 8669
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   posisi      8670 non-null   object
 1   deskripsi   8670 non-null   object
 2   perusahaan  8670 non-null   object
 3   lokasi      8670 non-null   object
 4   tahun       8670 non-null   int64
dtypes: int64(1), object(4)
memory usage: 338.8+ KB

In [522]:
df_merge.to_csv('data_merge.csv', index=False)

#from google.colab import files
#files.download('data_merge.csv')

**Dictionary**

In [523]:
education_level = {
    "Diploma": ["diploma"],

    "Associate Degree": [
        "associate degree", "associate's degree", "associates degree", "associate's"
    ],

    "Bachelor": [
        "bachelor", "bachelor's", "bachelor's degree", "bachelors",
        "bachelors degree", "bachelor degree", "bachelors' degree",
        "bachelorrsquos degree", "ba/bs", "bs/ba", "ba / bs", "bs / ba",
        "ba", "bs", "degree"
    ],

    "Undergraduate": [
        "undergraduate", "undergraduate degree", "undergraduates"
    ],

    "Master": [
        "master", "master's", "master's degree", "masters",
        "masters degree", "master degree", "masters' degree",
        "mba", "ma/ms", "ms/ma", "ms/ms", "ma / ms", "bs/ms", "ms", "ma"
    ],

    "Graduate Degree": [
        "graduate degree", "postgraduate degree", "postgraduate"
    ],

    "Doctorate": [
        "doctorate", "doctorate degree", "doctoral",
        "doctoral degree", "phd", "ph.d", "ph.d.", "postdoctoral"
    ],
}

education_major = {
    "STEM": [
        "stem", "science",
        "science technology engineering and mathematics",
        "science, technology, engineering and mathematics"
    ],
    "Quantitative Field": [
        "quantitative field",
        "quantitative fields",
        "quantitative discipline",
        "quantitative disciplines",
        "quantitative major",
        "quantitative background"
    ],
    "Computer": ["computer science"],
    "AI": ["artificial intelligence", "ai"],
    "Machine Learning": ["machine learning"],
    "Business": ["business intelligence", "business"],
    "Decision Science": ["decision science","decision sciences"],
    "Infromation System": ["information system", "information systems"],
    "Public Health": ["public health"],
    "Engineering": ["engineering", "engineer"],
    "Data Science": ["data science"],
    "Informatics": ["informatic", "informatics"],
    "Computational": [
        "computational science","computational mathematics",
        "computational biology", "computational"
    ],
    "Economics": ["economics", "economic"],
    "Financial": ["financial engineering", "financial", "finance"],
    "Quantitative Finance": ["quantitative finance"],
    "Data Management": ["data management"],
    "Data Visualization": ["data visualization"],
    "Biostatistics": [ "biostatistics", "bio"],
    "Biology": [ "biological", "biology"],
    "Physics": [ "physical", "physics"],
    "Chemistry": ["chemistry"],
    "Cognitive Science": ["cognitive science"],
    "Mathematics": [ "mathematics", "math", "mathematic"],
    "Marketing": ["marketing"],
    "Related Field": [
      "related field",
      "related fields",
      "related discipline",
      "related disciplines",
      "related major",
      "related majors",
      "or equivalent",
      "or equivalent experience"
    ]
}

career_level = {
    "Internship": [
        "intern", "internship", "co-op", "coop", "apprentice", "apprenticeship", "trainee"
    ],

    "Entry": [
        "entry", "entry level", "entry-level", "junior", "jr", "graduate",
        "new grad", "new graduate", "recent graduate", "early career",
        "associate", "associate analyst", "associate data analyst"
    ],

    "Mid": [
        "mid", "mid level", "mid-level", "mid senior", "mid-senior",
        "experienced", "professional", "staff"
    ],

    "Senior": [
        "senior", "sr", "principal", "expert", "specialist", "consultant"
    ],

    "Lead": [
        "lead", "team lead", "technical lead", "data lead",
        "lead data analyst", "data analyst lead", "analytics lead",
        "lead analyst", "lead data scientist"
    ],

    "Manager": [
        "manager"
    ],
}

hard_skills = {
    "SQL": ["sql", "tsql", "pl/sql"],
    "MySQL": ["mysql"],
    "PostgreSQL": ["postgresql", "postgres"],
    "SQL Server": ["sql server", "microsoft sql server", "ms sql server"],
    "Oracle": ["oracle"],
    "SQLite": ["sqlite"],
    "Teradata": ["teradata"],
    "Snowflake": ["snowflake"],
    "Redshift": ["redshift"],
    "BigQuery": ["bigquery", "big query"],
    "MongoDB": ["mongodb", "mongo db"],
    "NoSQL": ["nosql"],
    "Elasticsearch": ["elasticsearch", "elastic search"],
    "Redis": ["redis"],

    "Python": ["python"],
    "R": ["r"],
    "Scala": ["scala"],
    "Java": ["java"],
    "JavaScript": ["javascript", "js"],
    "C++": ["c++"],
    "C#": ["c#"],
    ".NET": [".net"],

    "Pandas": ["pandas"],
    "NumPy": ["numpy"],
    "SciPy": ["scipy"],
    "Statsmodels": ["statsmodels"],
    "Scikit-learn": ["scikit-learn", "sklearn"],
    "TensorFlow": ["tensorflow"],
    "PyTorch": ["pytorch"],

    "Excel": ["excel", "microsoft excel", "ms excel"],
    "Google Sheets": ["google sheets", "google spreadsheet", "spreadsheet"],
    "PowerPoint": ["powerpoint", "microsoft powerpoint", "ms powerpoint"],
    "MS Word": ["microsoft word", "ms word", "word"],
    "MS Access": ["microsoft access", "ms access"],
    "Visio": ["visio"],
    "SharePoint": ["sharepoint"],

    "Tableau": ["tableau"],
    "Power BI": ["power bi", "powerbi"],
    "Looker": ["looker"],
    "Looker Studio": ["looker studio", "google data studio"],
    "Qlik Sense": ["qlik sense", "qliksense"],
    "QlikView": ["qlikview", "qlik view"],
    "Domo": ["domo"],
    "Mongo": ["mongo"],
    "Redis": ["redis"],
    "Sisense": ["sisense"],
    "Cognos": ["cognos"],
    "MicroStrategy": ["microstrategy"],

    "SAS": ["sas"],
    "SPSS": ["spss"],
    "Stata": ["stata"],
    "MATLAB": ["matlab"],
    "Minitab": ["minitab"],

    "VBA": ["vba"],
    "DAX": ["dax"],
    "Power Query": ["power query"],
    "M Language": ["power query m", "m language"],

    "ETL": ["etl"],
    "ELT": ["elt"],
    "SSIS": ["ssis"],
    "SSRS": ["ssrs"],
    "SSAS": ["ssas"],
    "Informatica": ["informatica"],
    "Talend": ["talend"],
    "DataStage": ["datastage"],
    "dbt": ["dbt"],
    "Airflow": ["airflow"],
    "NiFi": ["apache nifi", "nifi"],

    "Spark": ["spark", "apache spark"],
    "PySpark": ["pyspark"],
    "Hadoop": ["hadoop"],
    "Hive": ["hive"],
    "Kafka": ["kafka"],

    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure", "microsoft azure"],
    "GCP": ["gcp", "google cloud", "google cloud platform"],
    "Azure Data Factory": ["azure data factory", "adf"],
    "Azure Synapse": ["azure synapse", "synapse"],
    "Databricks": ["databricks"],

    "Docker": ["docker"],
    "Kubernetes": ["kubernetes"],
    "Linux": ["linux"],
    "Unix": ["unix"],
    "Git": ["git"],
    "GitHub": ["github"],
    "GitLab": ["gitlab"],
    "Jira": ["jira"],

    "Data Modeling": ["data modeling", "data modelling"],
    "Data Warehousing": ["data warehouse", "data warehousing"],
    "Data Mining": ["data mining"],
    "Data Visualization": ["data visualization", "data visualisation"],
    "Statistical Analysis": ["statistical analysis"],
    "Statistics": ["statistics", "statistical"],
    "Regression": ["regression"],
    "Forecasting": ["forecasting"],
    "Predictive Analytics": ["predictive analytics"],
    "Machine Learning": ["machine learning", "ml"],
    "Deep Learning": ["deep learning"],
    "NLP": ["natural language processing", "nlp"],
    "A/B Testing": ["a/b testing", "a/b test", "ab testing"],

    "API": ["api", "rest api", "restful api"],
    "Salesforce": ["salesforce"],
    "SAP": ["sap", "sap hana"],
    "ERP": ["erp"],
    "CRM": ["crm"],
    "Epic": ["epic"],
    "Power Automate": ["power automate"],
    "Google Analytics": ["google analytics", "ga4", "google analytics 4"],

    "EHR": ["ehr", "electronic health records"],
    "EMR": ["electronic medical records", "emr"],

    "HIS": [
        "health information system",
        "health information systems",
        "his",
        "hospital information system",
        "hospital information systems",
    ],

    "HIPAA Compliance": [
        "hipaa", "hipaa compliance", "hipaa regulations",
        "health insurance portability and accountability act",
    ],
    "HL7": ["hl7", "health level seven","hl7 standards"],
    "FHIR": ["fhir", "fast healthcare interoperability resources"],
    "ICD Coding": ["icd", "icd-10", "icd 10", "international classification of diseases"],
    "CPT Coding": ["cpt", "current procedural terminology", "cpt coding"],

    "Reporting": ["reporting", "report", "reports"],
    "Data Visualization": ["data visualization", "visualizations", "visualization"],
    "Dashboard Development": ["dashboard", "kpi"],
    "Automation": ["automation"]
}

soft_skills = {
    "Communication": ["communication", "verbal communication", "written communication", "oral communication"],
    "Leadership": ["leadership", "leading teams", "team leadership"],
    "Problem Solving": ["problem solving", "problem-solving", "problem solver"],
    "Critical Thinking": ["critical thinking"],
    "Analytical Thinking": ["analytical thinking", "analytical skills", "analytical mindset", "critical analysis"],
    "Time Management": ["time management", "time-management"],
    "Teamwork": ["teamwork", "team player", "work in a team"],
    "Collaboration": ["collaboration", "collaborative", "cross-functional collaboration", "cross functional"],
    "Attention to Detail": ["attention to detail", "detail-oriented", "detail oriented", "detail focused"],
    "Interpersonal Skills": ["interpersonal skills", "interpersonal"],
    "Organizational Skills": ["organizational skills", "organization skills", "organizational ability"],
    "Multitasking": ["multitasking", "multi-tasking", "multitask"],
    "Presentation Skills": ["presentation skills", "presentation", "present findings"],
    "Negotiation": ["negotiation"],
    "Creativity": ["creativity", "creative thinking", "creative problem-solving", "creative solutions"],
    "Self-Motivated": ["self-motivated", "self starter", "self-starter", "self driven", "self-driven"],
    "Decision Making": ["decision making", "decision-making"],
    "Conflict Resolution": ["conflict resolution"],
    "Emotional Intelligence": ["emotional intelligence"],
    "Curiosity": ["curiosity", "curious"],
    "Work Ethic": ["work ethic"],
    "Mentoring": ["mentoring", "mentorship", "coach others", "coaching"],
    "Stakeholder Management": ["stakeholder management", "stakeholder engagement"],
    "Customer Service": ["customer service", "client service"],
    "Data Storytelling": ["data storytelling", "storytelling", "communicate insights"],
    "Adaptability": ["adaptability", "adaptable", "flexible", "flexibility"],
    "Initiative": ["initiative", "self initiative", "proactive", "proactively"],
    "Independent Work": ["work independently", "independently", "independent worker", "self sufficient"],
    "Continuous Learning": ["continuous learning", "lifelong learning", "learning mindset", "willing to learn", "eager to learn"],
    "Project Management": ["project management", "project coordination", "project planning"],
    "Prioritization": ["prioritization", "prioritize tasks", "prioritise tasks"],
    "Accountability": ["accountability", "accountable", "ownership", "take ownership"],
    "Adaptability to Change": ["change management", "adapt to change", "embrace change"],
    "Relationship Building": ["relationship building", "build relationships"],
    "Listening Skills": ["active listening", "listening skills"],
    "Professionalism": ["professionalism", "professional demeanor"],
}

state_mapping = {
    "al": "Alabama",
    "ak": "Alaska",
    "az": "Arizona",
    "ar": "Arkansas",
    "ca": "California",
    "co": "Colorado",
    "ct": "Connecticut",
    "de": "Delaware",
    "fl": "Florida",
    "ga": "Georgia",
    "hi": "Hawaii",
    "id": "Idaho",
    "il": "Illinois",
    "in": "Indiana",
    "ia": "Iowa",
    "ks": "Kansas",
    "ky": "Kentucky",
    "la": "Louisiana",
    "me": "Maine",
    "md": "Maryland",
    "ma": "Massachusetts",
    "mi": "Michigan",
    "mn": "Minnesota",
    "ms": "Mississippi",
    "mo": "Missouri",
    "mt": "Montana",
    "ne": "Nebraska",
    "nv": "Nevada",
    "nh": "New Hampshire",
    "nj": "New Jersey",
    "nm": "New Mexico",
    "ny": "New York",
    "nc": "North Carolina",
    "nd": "North Dakota",
    "oh": "Ohio",
    "ok": "Oklahoma",
    "or": "Oregon",
    "pa": "Pennsylvania",
    "ri": "Rhode Island",
    "sc": "South Carolina",
    "sd": "South Dakota",
    "tn": "Tennessee",
    "tx": "Texas",
    "ut": "Utah",
    "vt": "Vermont",
    "va": "Virginia",
    "wa": "Washington",
    "wv": "West Virginia",
    "wi": "Wisconsin",
    "wy": "Wyoming"
}

minimum_experience = {
    "0": [
        "0-2 years of experience", "0 - 2 years experience", "0-3 years of experience",
        "0 - 2 years of experience", "0-1 years’ experience", "0-1 years of experience",
        "0-1+ years of experience", "0-2 yr experience", "0-3 years’ experience",
        "0-1 year of experience", "0+ years of experience", "0 years of experience",
        "Minimum 0-3 years experience", "0-1 year experience", "0 to 2 years of experience",
        "0 to 1 years of experience", "0-3 years experience", "0-2 years’ experience",
        "0-2 years' experience", "0-2 yrs experience", "0 - 2+ years of experience",
        "minimum of 0-3 years of experience", "0 -2 years of experience",
        "0-4 years of experience", "Minimum of 0-2 years experience",
        "0-10 years of experience", "0 years experience", "0-5 years of experience",
        "0-4 years’ experience", "0-12+ years of experience", "0 years' experience",
    ],
    "1": [
        "1+ years of experience", "At least 1 year experience", "1 year of experience",
        "At least 1 year of experience", "1-3 years of experience", "1+ year of experience",
        "1-2 years of experience", "1 year expereince", "1+ years experience",
        "1 year experience", "1-2 years experience", "1+ year experience",
        "Minimum 1 year of experience", "Minimum 1 year experience", "1-5 years of experience",
        "1-3 years experience", "Min 1 year of experience", "1+ years’ experience",
        "1-year experience", "1-2 years' experience", "1 – 4 years of experience",
        "1 years' experience", "minimum of 1 year experience", "1 to 5 years of experience",
        "1-3 years’ experience", "1+ yearof experience", "Minimum 1- 2 years of experience",
        "1+ Years of Experience", "1-2+ yrs experience", "minimum 1-2 years of experience",
        "at least 1 year experience", "1-5 years experience", "At least 1+ years of experience",
        "1 years experience", "Minimum of 1+ years of experience", "1-2 years’ experience",
        "minimum of 1 year of experience", "1+ years' of experience",
        "Minimum of 1 year experience", "at least 1 year of experience", "1 year Experience",
        "Minimum of 1 year of experience", "Minimum 1+ years of experience",
        "1 - 2 years of experience", "At least 1-3 years of experience",
        "Minimum 1 to 3 years of experience", "1-3 Years of Experience",
        "1-4 years of experience", "Minimum 1 - 2 years' experience",
        "Minimum 1-2 Years' experience", "1-4 years experience",
        "1 to 2 years’experience", "Minimum of 1-2 years of experience",
        "Minimum 1 years’ experience", "1-3+ years of experience",
        "Minimum 1-2 years experience", "Minimum 1-2 years' experience",
        "1 to 2 years'experience", "1-4+ years of experience", "1+ yrs experience",
        "1 to 5 years’ experience", "Minimum 1-2 years’ experience",
        "at least 1 years’ experience", "1-5 years' experience",
        "Minimum 1-3 years of experience", "Minimum 1-year experience",
        "1+ years' experience", "1 Year of experience",
        "minimum of 1 years experience", "minimum 1-year experience",
        "1 - 5 years experience",
    ],
    "2": [
        "2+ years of experience", "2 years' experience", "2 years of experience",
        "2+ years experience", "2 years experience", "At least 2 years of experience",
        "2+ years’ experience", "2-3 years of experience", "2-4 years of experience",
        "At least 2 years experience", "2-5 years of experience", "2 years’ experience",
        "at least 2 years of experience", "Minimum 2 years of experience",
        "2-3 years experience", "2+ years' experience", "minimum 2 years",
        "2-4 years experience", "2 to 3 years of experience", "2-2 years of experience",
        "Minimum of 2 years of experience", "2 to 4 years of experience",
        "at least 2 years experience", "2-5 years experience",
        "Minimum 2 years experience", "minimum of 2 years of experience",
        "2 - 3 years of experience", "2+ Years of Experience",
        "2 to 5 years of experience", "Minimum of 2 years experience",
        "2-3 Years of Experience", "2 - 4 years of experience",
    ],
    "3": [
        "3+ years of experience", "3+ years experience", "3 years of experience",
        "3-5 years of experience", "3+ years' experience", "3+ years’ experience",
        "3 years' experience", "Minimum 3 years of experience",
        "At least 3 years of experience", "At least 3-5+ years of experience",
        "3-5 years experience", "3 years experience", "3 Years Experience",
        "Minimum of 3 years of experience", "3-4 years of experience",
        "3-4 years experience", "3 years’ experience", "at least 3 years of experience",
        "Minimum of 3 years experience", "3 - 5 years of experience",
        "3+ Years of Experience", "Minimum 3 years experience",
        "3 to 5 years of experience", "at least 3 years experience",
    ],
    "4": [
        "4+ years of experience", "4 years' experience", "4 years of experience",
        "At least 4 years of experience", "4+ years experience",
        "4 to 6 years of experience", "4 years' of experience", "4+ years’ experience",
        "4-6 years of experience", "4 years experience", "at least 4 years of experience",
        "Minimum 4 Years Experience", "4-6 year experience", "4-6 years experience",
        "4+ years' experience", "Minimum 4 years of experience",
        "4 years’ experience", "4-5 years of experience", "4 - 6 years of experience",
    ],
    "5": [
        "5+ years of experience", "5+ years experience", "5 years of experience",
        "5+ years' experience", "5+ years’ experience", "at least 5 years of experience",
        "Minimum 5 years' experience", "At least 5 years of experience",
        "minimum of 5 years of experience", "Minimum of 5 years of experience",
        "5 years' experience", "Minimum 5 years of experience", "5-7 years experience",
        "5-7 years of experience", "5 years experience", "5 years’ experience",
        "5-8 years of experience", "5-10 years of experience",
        "Minimum of 5 years experience",
    ],
    "6": [
        "6 years' experience", "6+ years of experience", "6 years of experience",
        "6+ years experience", "6-10 years of experience", "Minimum 6 years of experience",
        "minimum of 6 years of experience", "6 Years Experience",
        "6 + years' experience", "6 + years’ experience", "6+ years’ experience",
        "6+ years' experience", "6-8 Years’ experience", "6 years’ experience",
        "6 years experience",
    ],
    "7": [
        "7-10 years' experience", "7+ years of experience", "7+ years' experience",
        "7 years of experience", "At least 7+ years experience", "7-10 years of experience",
        "7+ years experience", "7+ years’ experience", "7 years’ experience",
        "7 years experience", "at least 7 years’ experience", "7+ Years Experience",
        "Minimum 7 years of experience", "7+ Years of experience",
        "At least 7 years of experience",
    ],
    "8": [
        "8 years' experience", "8+ years of experience", "8 Years Experience",
        "8-10 years of experience", "Minimum 8 Years' experience", "8 years of experience",
        "8 years experience", "8+ years' experience", "at least 8+ years of experience",
        "At least 8 years of experience", "minimum of 8 years experience",
        "8+ years experience", "8+ years’ experience", "8+ Years of experience",
        "8-12 years' experience",
    ],
    "9": [
        "9+ years of experience", "at least 9 years of experience",
        "Minimum 9 years of experience", "9+ years of exp.", "9 years experience",
        "minimum 9-10 years of experience",
    ],
    "10": [
        "10+ years of experience", "10 years of experience", "10+ years’ experience",
        "10+ years' experience", "10 years experience", "10+ years experience",
        "Minimum of 10 years experience", "minimum of 10+ years of experience",
        "10+ Years of Experience", "10+ years Experience", "10-12+ years of experience",
        "Minimum of 10 years of experience", "10 + years' experience",
        "10-12 years experience",
    ],
    "12": [
        "12+ years of experience", "at least 12 years of experience",
        "12 Years Experience", "12-15 years experience", "minimum of 12 years of experience",
        "12-15 years’ experience", "12 years of experience",
    ],
    "14": [
        "14 years of experience", "14+ years experience", "14+ years of experience",
    ],
    "15": [
        "15+ years of experience",
    ],
    "16": [
        "At least 16 years of experience",
    ],
    "18": [
        "18+ years of experience",
    ],
}

**Text Preprocessing**

In [524]:
def preprocess_text(text):

    if pd.isna(text):
        return ""

    text = str(text).lower()

    text = text.replace("–", "-")
    text = text.replace("—", "-")
    text = text.replace("−", "-")
    text = text.replace("’", "'")

    text = re.sub(
        r'(\d+)\s+(\d+)\s+(years?|yrs?)',
        r'\1-\2 \3',
        text
    )
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [525]:
def preprocess_location(text):

    if pd.isna(text):
        return ""

    text = str(text).lower()
    text = text.strip()
    text = text.replace(".", "")
    text = re.sub(r"\s+", " ", text)

    return text

In [526]:
def preprocess_company(text):

    if pd.isna(text):
        return ""

    text = str(text)
    text = re.sub(r"[\n\t]+", " ", text)
    text = re.sub(
        r"\s+\d+\.\d+$",
        "",
        text
    )
    text = re.sub(
        r"\s+\d+$",
        "",
        text
    )
    text = re.sub(r"\s+", " ", text)

    return text.strip()

**Normalisasi**

In [527]:
def build_pattern(dictionary):
    patterns = {}

    for key, values in dictionary.items():

        vals = sorted(values, key=len, reverse=True)

        escaped = []

        for v in vals:
            escaped.append(re.escape(v))

        patterns[key] = re.compile(
            r'\b(?:' + '|'.join(map(re.escape, vals)) + r')\b'
        )

    return patterns


education_pattern = build_pattern(education_level)
major_pattern = build_pattern(education_major)
career_pattern = build_pattern(career_level)
hard_pattern = build_pattern(hard_skills)
soft_pattern = build_pattern(soft_skills)

In [528]:
number_words = {
    "zero":0,
    "one":1,
    "two":2,
    "three":3,
    "four":4,
    "five":5,
    "six":6,
    "seven":7,
    "eight":8,
    "nine":9,
    "ten":10,
    "eleven":11,
    "twelve":12,
    "thirteen":13,
    "fourteen":14,
    "fifteen":15,
    "sixteen":16,
    "seventeen":17,
    "eighteen":18,
    "nineteen":19,
    "twenty":20
}

In [529]:
def extract_education(text):
    if pd.isna(text):
        return "Unspecified"

    text = preprocess_text(text)
    result = []

    for edu, keywords in education_level.items():
        pattern = r'\b(' + '|'.join([re.escape(k) for k in keywords]) + r')\b'
        if re.search(pattern, text, flags=re.IGNORECASE):
            result.append(edu)

    return ", ".join(sorted(set(result))) if result else "Unspecified"

In [530]:
def extract_major(text):

    if pd.isna(text):
        return None

    text = preprocess_text(text)

    result = []

    for major, pattern in major_pattern.items():

        if pattern.search(text):

            result.append(major)

    return ", ".join(sorted(set(result))) if result else "Other"

In [531]:
def extract_hard_skill(text):

    if pd.isna(text):
        return None

    text = preprocess_text(text)

    result = []

    for skill, pattern in hard_pattern.items():

        if pattern.search(text):

            result.append(skill)

    return ", ".join(sorted(set(result))) if result else "Other"

In [532]:
def extract_soft_skill(text):

    if pd.isna(text):
        return None

    text = preprocess_text(text)

    result = []

    for skill, pattern in soft_pattern.items():

        if pattern.search(text):

            result.append(skill)

    return ", ".join(sorted(set(result))) if result else "Other"

In [533]:
def extract_experience(text):
    if pd.isna(text):
        return None

    text = preprocess_text(text)

    for word, num in number_words.items():
        text = re.sub(rf'\b{word}\b', str(num), text)

    text = re.sub(
        rf'\b(?:over|nearly|about|around|almost|approximately)\s+\d+\s*(?:years?|yrs?)\b(?:\s+ago)?',
        '',
        text
    )
    text = re.sub(
        rf'\b\d+\s*(?:years?|yrs?)\s+ago\b',
        '',
        text
    )

    if re.search(r'fresh\s*graduate|freshers?|no\s*experience|entry\s*level', text):
        return 0

    m = re.search(r'(\d+)\+?\s*(?:or\s+more)?\s*(?:-|to)\s*(\d+)\+?\s*(?:or\s+more)?\s*(?:years?|yrs?)', text)
    if m:
        return int(m.group(1))

    patterns = [
        r'(?:minimum|min\.?|at\s+least|required|requirement|minimum\s+of)\s*(\d+)\+?\s*(?:years?|yrs?)',
        r'(\d+)\+?\s*(?:years?|yrs?)\s*(?:of\s+)?(?:professional\s+)?experience',
        r'experience\s*(?:of\s*)?(\d+)\+?\s*(?:years?|yrs?)'
    ]

    for pattern in patterns:
        m = re.search(pattern, text)
        if m:
            return int(m.group(1))

    for exp, variants in minimum_experience.items():
        for v in variants:
            if preprocess_text(v) in text:
                return int(exp)

    m = re.search(r'(\d+)\+?\s*(?:years?|yrs?)', text)
    if m:
        return int(m.group(1))

    return None

In [534]:
def infer_level_from_experience(exp):

    if exp is None:
        return None

    if exp == 0:
        return "Entry"

    elif exp <= 2:
        return "Entry"

    elif exp <= 4:
        return "Mid"

    elif exp <= 7:
        return "Senior"

    elif exp <= 10:
        return "Lead"

    else:
        return "Manager"

In [535]:
def extract_level(position, description):

    if pd.notna(position):

        for level, pattern in career_pattern.items():

            if pattern.search(position):
                return level

    exp = extract_experience(description)

    return infer_level_from_experience(exp)

In [536]:
def extract_state(location):

    if pd.isna(location):
        return "Unknown"

    location = preprocess_location(location)

    if "remote" in location:
            return "Remote"

    match = re.search(
        r',\s*([a-z]{2})\b',
        location
    )

    if match:

        code = match.group(1)

        if code in state_mapping:
            return state_mapping[code]


    for code, state in state_mapping.items():

        if state.lower() in location:
            return state


    if "united states" in location or "usa" in location:
        return "Unknown"


    return "Unknown"

In [537]:
tqdm.pandas()

df_merge["deskripsi_clean"] = df_merge["deskripsi"].progress_apply(
    preprocess_text
)

df_merge["posisi_clean"] = df_merge["posisi"].progress_apply(
    preprocess_text
)

df_merge["pendidikan"] = df_merge["deskripsi_clean"].progress_apply(
    extract_education
)

df_merge["jurusan"] = df_merge["deskripsi_clean"].progress_apply(
    extract_major
)

df_merge["pengalaman"] = df_merge["deskripsi_clean"].progress_apply(
    extract_experience
)

df_merge["hard_skill"] = df_merge["deskripsi_clean"].progress_apply(
    extract_hard_skill
)

df_merge["soft_skill"] = df_merge["deskripsi_clean"].progress_apply(
    extract_soft_skill
)

df_merge["level"] = df_merge.progress_apply(

    lambda row: extract_level(
        row["posisi_clean"],
        row["deskripsi_clean"]
    ),

    axis=1
)

df_merge["lokasi"] = df_merge["lokasi"].progress_apply(
    extract_state
)

df_merge["perusahaan"] = df_merge["perusahaan"].progress_apply(
    preprocess_company
)

df_merge['deskripsi_len'] = df_merge['deskripsi'].fillna("").str.split().apply(len)

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

  0%|          | 0/8670 [00:00<?, ?it/s]

In [538]:
df_edu = df_merge[['pendidikan']].copy()
df_edu = df_edu.explode('pendidikan')
df_edu['pendidikan'].value_counts()

pendidikan
Bachelor                                                       2938
Bachelor, Master                                               2472
Unspecified                                                    1629
Master                                                          534
Bachelor, Undergraduate                                         226
Bachelor, Doctorate, Master                                     177
Associate Degree, Bachelor                                      101
Bachelor, Diploma, Doctorate, Master                             98
Bachelor, Diploma                                                81
Bachelor, Master, Undergraduate                                  60
Bachelor, Diploma, Master                                        50
Associate Degree, Bachelor, Master                               36
Bachelor, Graduate Degree, Master                                32
Diploma                                                          32
Bachelor, Graduate Degree                                        29
Associate Degree, Bachelor, Diploma                              21
Diploma, Undergraduate                                           20
Bachelor, Graduate Degree, Undergraduate                         16
Bachelor, Diploma, Undergraduate                                 16
Associate Degree, Bachelor, Diploma, Master                      15
Bachelor, Doctorate                                              13
Diploma, Master                                                  12
Doctorate, Master                                                11
Doctorate                                                        11
Bachelor, Graduate Degree, Master, Undergraduate                  8
Bachelor, Doctorate, Graduate Degree, Master                      4
Bachelor, Doctorate, Master, Undergraduate                        4
Associate Degree, Bachelor, Doctorate, Master                     4
Undergraduate                                                     4
Bachelor, Doctorate, Graduate Degree, Master, Undergraduate       4
Bachelor, Doctorate, Undergraduate                                3
Associate Degree, Bachelor, Diploma, Graduate Degree              2
Bachelor, Diploma, Master, Undergraduate                          1
Doctorate, Master, Undergraduate                                  1
Bachelor, Doctorate, Graduate Degree                              1
Associate Degree, Bachelor, Diploma, Undergraduate                1
Graduate Degree, Master                                           1
Master, Undergraduate                                             1
Doctorate, Undergraduate                                          1
Name: count, dtype: int64

In [539]:
df_merge.describe()

             tahun   pengalaman  deskripsi_len
count  8670.000000  6169.000000    8670.000000
mean   2021.667589     4.272978     533.784429
std       1.698798     6.547694     309.553709
min    2020.000000     0.000000       5.000000
25%    2020.000000     2.000000     302.000000
50%    2022.000000     3.000000     480.000000
75%    2023.000000     5.000000     716.000000
max    2025.000000   160.000000    2142.000000

In [540]:
df_merge[df_merge['pengalaman'] > 20]

,posisi,deskripsi,perusahaan,lokasi,tahun,deskripsi_clean,posisi_clean,pendidikan,jurusan,pengalaman,hard_skill,soft_skill,level,deskripsi_len
296,Data Analyst,Job Description\nPaladin Consulting is current...,Paladin Consulting Inc,Utah,2020,job description paladin consulting is currentl...,data analyst,"Bachelor, Master",Business,30.0,"Excel, MS Word, PowerPoint","Attention to Detail, Communication, Customer S...",Manager,371
432,Data Analyst Manager,"OUR CLIENT\n\nHeadquartered in Los Angeles, ou...",Oakwood Search - CHURN,California,2020,"our client headquartered in los angeles, our c...",data analyst manager,"Bachelor, Master","Business, Computer, STEM",30.0,"ETL, Reporting",Other,Manager,274
565,Data Analyst,Job DescriptionIf you are an experienced Data ...,Bartech Group,Illinois,2020,job descriptionif you are an experienced data ...,data analyst,"Bachelor, Diploma, Master",Business,41.0,"Automation, Data Modeling, Excel, MS Access, R...","Analytical Thinking, Attention to Detail, Comm...",Manager,487
572,Data Analyst,Job Description\nJob Title: Data Analyst\n\nRe...,Accounting Aid Society,Illinois,2020,job description job title: data analyst report...,data analyst,Unspecified,"Business, Computer, Data Management, Financial...",45.0,"Data Visualization, Excel, MS Word, Reporting,...","Adaptability, Attention to Detail, Collaborati...",Manager,558
584,Data Analyst,Data Analyst #411045Job Description:\n\nIf you...,"Fast Switch, LTD",Illinois,2020,data analyst #411045job description: if you ar...,data analyst,Unspecified,Other,22.0,"EMR, SAS, SQL","Adaptability, Initiative",Manager,523
590,Data Analyst/Programmer,Job Description\nPosition Summary\n\nData Anal...,ABS Graphics,Illinois,2020,job description position summary data analyst ...,data analyst/programmer,"Bachelor, Master","Computer, Related Field, STEM",30.0,"Automation, Excel, SQL","Communication, Initiative, Teamwork",Manager,335
595,Senior Global Data Analyst / Power BI Dashboar...,Senior Global Data Analyst / Power BI Dashboar...,ALERE,Illinois,2020,senior global data analyst / power bi dashboar...,senior global data analyst / power bi dashboar...,Bachelor,"Business, Computer, Data Science, Economics, E...",125.0,"Azure, DAX, Dashboard Development, Data Modeli...","Problem Solving, Teamwork",Senior,449
731,Senior Data Analyst,Job DescriptionIf you are an experienced Senio...,Bartech Group,Arizona,2020,job descriptionif you are an experienced senio...,senior data analyst,Bachelor,"Business, Financial, Related Field",41.0,"Excel, Reporting","Attention to Detail, Communication, Decision M...",Senior,691
1206,EDI Data Analyst,Expertise in Healthcare data analytics\n\nExpe...,KGS,Texas,2020,expertise in healthcare data analytics experti...,edi data analyst,Unspecified,"Business, Financial",40.0,"Data Mining, Excel, Reporting, SAS, SSIS, SSRS",Leadership,Manager,224
1350,Data Analyst,"Overview:\n\nParks Heating and Cooling, a lead...",Parks Heating & Cooling,North Carolina,2020,"overview: parks heating and cooling, a leading...",data analyst,Unspecified,Business,40.0,"Data Mining, ETL, Excel, JavaScript, Reporting...","Analytical Thinking, Attention to Detail",Manager,303
1681,Scientific Data Analyst - Long term contract w...,Job Description\nPosition: Scientific Data Ana...,Joulé Clinical Staffing,Illinois,2020,job description position: scientific data anal...,scientific data analyst - long term contract w...,Master,"Data Management, Data Visualization, Engineeri...",40.0,"Data Visualization, Excel, MS Access, Power BI...",Communication,Manager,648
2088,Data Analyst,"For the past 24 years, we've been doing work t...",Forum One,Virginia,2020,"for the past 24 years, we've been doing work t...",data analyst,"Bachelor, Undergraduate","Computer, Data Visualization, Marketing, Mathe...",24.0,"Data Visualization, Excel, Google Analytics, G...","Accountability, Adaptability, Collaboration, C...",Manager,584
2481,Genomic Data Analyst,Company Description\nEurofins Scientific is an...,Eurofins,Massachusetts,2020,company description eurofins scientific is an ...,genomic data analyst,"Bachelor, Doctorate, Master","Biology, Computational, Related Field, STEM",30.0,"Python, R",Other,Manager,374
2485,Technology & Data Analyst,Responsibilities:\nThe analysts support will b...,Bridge Over Troubled Waters,Massachusetts,2020,responsibilities: the analysts support will be...,technology & data analyst,Bachelor,Physics,48.0,"Reporting, SAP","Communication, Creativity, Leadership, Problem...",Manager,440
2494,Data Analyst-Saas Product,Enterprise B2B company is looking to hire a se...,"Management Decisions, Inc.",Massachusetts,2020,enterprise b2b company is looking to hire a se...,data analyst-saas product,Unspecified,"AI, Business, Data Visualization",30.0,"Data Visualization, Looker, Machine Learning, ...",Other,Manager,238
2658,Data Analyst,BACKGROUND: MDC Research is a high-touch marke...,MDC Research,Oregon,2020,background: mdc research is a high-touch marke...,data analyst,Bachelor,"Business, Data Management",40.0,"Excel, PowerPoint, Reporting, SPSS","Collaboration, Creativity, Customer Service, I...",Manager,555
2945,Scientific Data Analyst - Long term contract w...,Job Description\nPosition: Scientific Data Ana...,Joulé Clinical Staffing,Georgia,2020,job description position: scientific data anal...,scientific data analyst - long term contract w...,Master,"Data Management, Data Visualization, Engineeri...",40.0,"Data Visualization, Excel, MS Access, Power BI...",Communication,Manager,648
3003,Senior Data Analyst,Senior Data Analyst\nCareer Site Location\n\n\...,Myers and Stauffer,Georgia,2020,"senior data analyst career site location ga, a...",senior data analyst,"Bachelor, Master","Data Management, Financial, Related Field",40.0,"R, Reporting, SAS, SQL, SQL Server, Statistics","Attention to Detail, Communication, Leadership...",Senior,597
3119,Data Analyst,Job Description\n\n\nJob #: 1075931\n\nApex Sy...,Apex Systems,North Carolina,2020,job description job #: 1075931 apex systems is...,data analyst,Unspecified,"Business, Financial",70.0,"Data Warehousing, Excel, Jira, Oracle, Reporti...",Time Management,Manager,692
3131,Scientific Data Analyst - Long term contract w...,Job Description\nPosition: Scientific Data Ana...,Joulé Clinical Staffing,North Carolina,2020,job description position: scientific data anal...,scientific data analyst - long term contract w...,Master,"Data Management, Data Visualization, Engineeri...",40.0,"Data Visualization, Excel, MS Access, Power BI...",Communication,Manager,648
3528,Data Analyst,We are social entrepreneurs and we are changin...,NECCO,Ohio,2020,we are social entrepreneurs and we are changin...,data analyst,"Bachelor, Diploma","Business, Computer, Data Management, Financial...",21.0,"Dashboard Development, Data Modeling, Data War...","Collaboration, Communication, Leadership, Self...",Manager,442
3615,Risk Reporting Data Analyst,STRATEGIC STAFFING SOLUTIONS HAS AN OPENING!St...,Strategic Staffing Solutions,Missouri,2020,strategic staffing solutions has an opening!st...,risk reporting data analyst,Bachelor,"Business, Financial",28.0,"Dashboard Development, Data Modeling, Excel, M...","Adaptability, Presentation Skills, Project Man...",Manager,892
3636,Data Analyst,Job DescriptionIf you are an experienced Data ...,Bartech Group,Pennsylvania,2020,job descriptionif you are an experienced data ...,data analyst,Bachelor,"Business, Financial, Related Field",41.0,"Excel, Reporting","Attention to Detail, Communication, Decision M...",Manager,664
3752,Scientific Data Analyst - Long term contract w...,Job Description\nPosition: Scientific Data Ana...,Joulé Clinical Staffing,New York,2020,job description position: scientific data anal...,scientific data analyst - long term contract w...,Master,"Data Management, Data Visualization, Engineeri...",40.0,"Data Visualization, Excel, MS Access, Power BI...",Communication,Manager,648
3922,Senior Global Data Analyst / Power BI Dashboar...,"DO WORK THAT MATTERS\n\nAt Abbott, diverse ide...",Abbott Laboratories,Unknown,2020,"do work that matters at abbott, diverse ideas,...",senior global data analyst / power bi dashboar...,Bachelor,"Business, Computer, Data Science, Economics, E...",125.0,"Azure, DAX, Dashboard Development, Data Modeli...","Problem Solving, Teamwork",Senior,452
3988,Data Analyst - California Only - Campus Recrui...,CAPGEMINI STAFF CONSULTANT ROLE\n\nWho are we?...,Capgemini,Unknown,2020,capgemini staff consultant role who are we? • ...,data analyst - california only - campus recrui...,Bachelor,"Business, Computer, Data Science, Engineering,...",50.0,"AWS, Azure, ETL, GCP, Hadoop, Java, JavaScript...","Adaptability, Collaboration, Communication, Le...",Manager,1468
3989,Data Analyst - All Locations Non-California - ...,CAPGEMINI STAFF CONSULTANT ROLE\n\nWho are we?...,Capgemini,Unknown,2020,capgemini staff consultant role who are we? • ...,data analyst - all locations non-california - ...,Bachelor,"Business, Computer, Data Science, Engineering,...",50.0,"AWS, Azure, ETL, GCP, Hadoop, Java, JavaScript...","Adaptability, Collaboration, Communication, Le...",Manager,1468
3995,Senior Global Data Analyst / Power BI Dashboar...,"DO WORK THAT MATTERS\n\nAt Abbott, diverse ide...",Abbott,Remote,2020,"do work that matters at abbott, diverse ideas,...",senior global data analyst / power bi dashboar...,Bachelor,"Business, Computer, Data Science, Economics, E...",125.0,"Azure, DAX, Dashboard Development, Data Modeli...","Problem Solving, Teamwork",Senior,452
4167,Insurance – Data Analyst – REMOTE,Put your Insurance Experience to work – FROM H...,WAHVE,Missouri,2022,put your insurance experience to work - from h...,insurance - data analyst - remote,Unspecified,"Business, Financial",25.0,"CRM, Data Warehousing, Excel, JavaScript, Powe...","Adaptability, Customer Service, Independent Wo...",Manager,402
4221,Insurance – Data Analyst – REMOTE,Put your Insurance Experience to work – FROM H...,WAHVE,California,2022,put your insurance experience to work - from h...,insurance - data analyst - remote,Unspecified,"Business, Financial",25.0,"CRM, Data Warehousing, Excel, JavaScript, Powe...","Adaptability, Customer Service, Independent Wo...",Manager,402
4224,Reporting/Data Analyst,Kitestring is a 20+-million-dollar company wit...,Kitestring,Arkansas,2022,kitestring is a 20+-million-dollar company wit...,reporting/data analyst,Unspecified,Business,24.0,"Data Warehousing, SQL, Statistical Analysis, S...",Other,Manager,193
4553,Insurance – Data Analyst – REMOTE,Put your Insurance Experience to work – FROM H...,WAHVE,California,2022,put your insurance experience to work - from h...,insurance - data analyst - remote,Unspecified,"Business, Financial",25.0,"CRM, Data Warehousing, Excel, JavaScript, Powe...","Adaptability, Customer Service, Independent Wo...",Manager,401
4883,Data Analyst (Full Time) United States,"What You’ll Do\n• Identify, analyze, and inter...",Cisco,California,2022,"what you'll do • identify, analyze, and interp...",data analyst (full time) united states,Bachelor,"Business, Machine Learning, Marketing",36.0,"Automation, Machine Learning, Reporting, Stati...","Accountability, Creativity, Leadership",Manager,550
5034,Reporting/Data Analyst,Kitestring is a 20+-million-dollar company wit...,Kitestring,Arkansas,2022,kitestring is a 20+-million-dollar company wit...,reporting/data analyst,Unspecified,Business,24.0,"Data Warehousing, SQL, Statistical Analysis, S...",Other,Manager,195
5586,Fuel Data Analyst Intern (Summer 2023),Req ID: 408370\n• This position will be locate...,Love's Travel Stops,Oklahoma,2023,req id: 408370 • this position will be located...,fuel data analyst intern (summer 2023),"Bachelor, Diploma, Master","Business, Data Science, Physics, Related Field...",55.0,"Excel, PowerPoint, Reporting, Snowflake, Stati...","Attention to Detail, Communication, Critical T...",Internship,529
5617,Senior Data Analyst,Job Description\n\nOracle Cerner is seeking a ...,Oracle,Missouri,2023,job description oracle cerner is seeking a sen...,senior data analyst,Unspecified,Business,40.0,"Data Visualization, Oracle, Statistics","Leadership, Presentation Skills",Senior,417
5781,Insurance Data Analyst REMOTE,Put your Insurance Experience to work – FROM H...,Work At Home Vintage Experts,Kansas,2023,put your insurance experience to work - from h...,insurance data analyst remote,Unspecified,"Business, Financial",25.0,"CRM, Data Warehousing, Excel, JavaScript, Powe...","Customer Service, Independent Work, Leadership",Manager,432
6193,Data Analyst - Reporting,Job Details\n\nDescription...\n\nAt INTRUST Ba...,INTRUST Bank,Kansas,2023,"job details description... at intrust bank, pr...",data analyst - reporting,Bachelor,"Business, Financial, Infromation System, Physics",145.0,"Automation, Excel, HIS, MS Word, PowerPoint, R...","Accountability, Adaptability, Analytical Think...",Manager,1020
6547,Data Analyst,"Description\n\nAt INTRUST Bank, principles and...",INTRUST Bank,Kansas,2023,"description at intrust bank, principles and pe...",data analyst,Bachelor,"Business, Financial, Infromation System, Physics",145.0,"Automation, Excel, HIS, MS Word, PowerPoint, R...","Accountability, Adaptability, Analytical Think...",Manager,1125
7454,"Master Data Analyst, Inventory - Hybrid","With a mantra of Empowering Human Potential, H...","Hanger, Inc.",Texas,2024,"with a mantra of empowering human potential, h...","master data analyst, inventory - hybrid","Bachelor, Master","Business, Data Management, Engineering, Financ...",160.0,"Automation, Excel, Oracle, Reporting","Collaboration, Communication, Critical Thinkin...",Manager,1045
7522,URBN Senior HRIS Data Analyst,"URBN Urban Outfitters, Inc. (www.urbn.com) is ...","URBN (Urban Outfitters, Anthropologie Group, F...",Pennsylvania,2024,"urbn urban outfitters, inc. (www.urbn.com) is ...",urbn senior hris data analyst,Bachelor,"Business, Data Visualization, Physics, Related...",50.0,"API, Cognos, Data Visualization, Excel, Looker...","Accountability, Adaptability to Change, Attent...",Senior,558
7523,Data Analyst,International SOS is the world’s leading medic...,International SOS,Pennsylvania,2024,international sos is the world's leading medic...,data analyst,Bachelor,"Business, Computer, Data Visualization, STEM",35.0,"AWS, Data Modeling, Data Visualization, ETL, E...","Adaptability, Attention to Detail, Collaborati...",Manager,586
7536,HR Data Analyst,Company Overview\nSleep Number team members ar...,Sleep Number Corporation,Minnesota,2024,company overview sleep number team members are...,hr data analyst,Bachelor,"Business, Data Science, Data Visualization, Fi...",35.0,"Data Visualization, Excel, MS Word, Power BI, ...","Adaptability, Continuous Learning, Customer Se...",Manager,1370
7559,Clinical Data Analyst - Biostatistics Team,"Our corporate activities are growing rapidly, ...",Medpace,Ohio,2024,"our corporate activities are growing rapidly, ...",clinical data analyst - biostatistics team,Bachelor,"Biostatistics, Data Visualization, Mathematics...",30.0,"Data Visualization, Power BI, Reporting, Stati...","Adaptability, Leadership",Manager,427
7562,Sr. Investment Data Analyst,Welcome to Western & Southern Financial Group ...,"Fort Washington Investment Advisors, Inc.",Ohio,2024,welcome to western & southern financial group ...,sr. investment data analyst,Unspecified,"Business, Financial",130.0,"Data Visualization, Excel, SQL, SQL Server","Attention to Detail, Collaboration, Communicat...",Senior,436
7662,"Master Data Analyst, Inventory - Hybrid",Why Us?\nWith a mantra of Empowering Human Pot...,"Hanger, Inc.",Texas,2024,why us? with a mantra of empowering human pote...,"master data analyst, inventory - hybrid","Bachelor, Master","Business, Data Management, Engineering, Financ...",160.0,"Automation, Excel, Oracle, Reporting","Collaboration, Communication, Critical Thinkin...",Manager,1064
7670,Senior Water Utility Data Analyst,Golden State Water Company is one of the large...,Golden State Water Company,California,2024,golden state water company is one of the large...,senior water utility data analyst,Bachelor,"Business, Computer, Data Management, Data Visu...",90.0,"Azure, Data Modeling, Data Visualization, ETL,...","Accountability, Adaptability, Attention to Det...",Senior,1094
7835,Senior Data Analyst,CenterPoint Energy and its predecessor compani...,CenterPoint Energy,Texas,2024,centerpoint energy and its predecessor compani...,senior data analyst,Bachelor,"Business, Computer, Data Management, Data Scie...",150.0,"AWS, Automation, Azure, BigQuery, Data Modelin...","Adaptability, Analytical Thinking, Attention t...",Senior,1003
7987,Data Analyst,"Iris's Direct client, one of the world's large...",Iris Software Inc.,New Jersey,2024,"iris's direct client, one of the world's large...",data analyst,Unspecified,"Business, Data Management, Engineering, Financial",30.0,Other,"Adaptability, Decision Making",Manager,285
8164,RESEARCH DATA ANALYST II,Equal Opportunity Employer\nThe State of Calif...,Employment Development Department,California,2024,equal opportunity employer the state of califo...,research data analyst ii,Unspecified,"Business, Economics, Physics",70.0,"Reporting, Statistics",Independent Work,Manager,1209
8539,Data Analyst,Top Skills' Details\n\n\nExperience addressing...,TEKsystems,California,2025,top skills' details experience addressing long...,data analyst,"Bachelor, Master","AI, Engineering, Machine Learning, Related Field",25.0,"Data Mining, HIS, Machine Learning, PySpark, P...","Collaboration, Communication",Manager,863

In [541]:
df_merge = df_merge[
[
    "posisi",
    "perusahaan",
    "lokasi",
    "pendidikan",
    "jurusan",
    "pengalaman",
    "level",
    "hard_skill",
    "soft_skill",
    "deskripsi",
    "deskripsi_len",
    "tahun"
  ]
]

In [542]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8670 entries, 0 to 8669
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   posisi         8670 non-null   object
 1   perusahaan     8670 non-null   object
 2   lokasi         8670 non-null   object
 3   pendidikan     8670 non-null   object
 4   jurusan        8670 non-null   object
 5   pengalaman     6169 non-null   float64
 6   level          7016 non-null   object
 7   hard_skill     8670 non-null   object
 8   soft_skill     8670 non-null   object
 9   deskripsi      8670 non-null   object
 10  deskripsi_len  8670 non-null   int64
 11  tahun          8670 non-null   int64
dtypes: float64(1), int64(2), object(9)
memory usage: 812.9+ KB

In [544]:
df_merge["level"] = df_merge["level"].fillna("Unspecified")
df_merge.loc[df_merge["pengalaman"] >= 20, "pengalaman"] = -1
df_merge["pengalaman"] = df_merge["pengalaman"].fillna(-1)

In [545]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8670 entries, 0 to 8669
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   posisi         8670 non-null   object
 1   perusahaan     8670 non-null   object
 2   lokasi         8670 non-null   object
 3   pendidikan     8670 non-null   object
 4   jurusan        8670 non-null   object
 5   pengalaman     8670 non-null   float64
 6   level          8670 non-null   object
 7   hard_skill     8670 non-null   object
 8   soft_skill     8670 non-null   object
 9   deskripsi      8670 non-null   object
 10  deskripsi_len  8670 non-null   int64
 11  tahun          8670 non-null   int64
dtypes: float64(1), int64(2), object(9)
memory usage: 812.9+ KB

In [546]:
df_merge.head(15)

,posisi,perusahaan,lokasi,pendidikan,jurusan,pengalaman,level,hard_skill,soft_skill,deskripsi,deskripsi_len,tahun
0,"Data Analyst, Center on Immigration and Justic...",Vera Institute of Justice,New York,Unspecified,Data Management,1.0,Entry,"AWS, Git, GitHub, Python, R, Reporting, SQL, S...","Accountability, Attention to Detail, Collabora...",Are you eager to roll up your sleeves and harn...,1020,2020
1,Quality Data Analyst,Visiting Nurse Service of New York,New York,"Bachelor, Master","Biostatistics, Business, Computer, Data Scienc...",2.0,Entry,"Dashboard Development, Excel, MS Word, MicroSt...","Communication, Interpersonal Skills, Leadershi...",Overview\n\nProvides analytical and technical ...,600,2020
2,"Senior Data Analyst, Insights & Analytics Team...",Squarespace,New York,"Bachelor, Doctorate, Master","Data Science, Data Visualization, Engineering,...",-1.0,Senior,"Data Modeling, Data Visualization, Excel, Look...","Analytical Thinking, Curiosity, Mentoring, Pre...",We’re looking for a Senior Data Analyst who ha...,701,2020
3,Data Analyst,Celerity,New York,Bachelor,"Business, Data Visualization, Engineering, Fin...",2.0,Entry,"Automation, Data Visualization, ETL, Power BI,...","Accountability, Adaptability, Analytical Think...",Requisition NumberRR-0001939\nRemote:Yes\nWe c...,767,2020
4,Reporting Data Analyst,FanDuel,New York,Bachelor,Engineering,1.0,Entry,"Automation, Data Visualization, Excel, Python,...","Accountability, Adaptability, Mentoring",ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,529,2020
5,Data Analyst,Point72,New York,Bachelor,Financial,-1.0,Unspecified,"Excel, Java, MS Word, Python, SQL","Attention to Detail, Communication, Interperso...",About Cubist\nCubist Systematic Strategies is ...,370,2020
6,Business/Data Analyst (FP&A),Two Sigma,New York,Bachelor,"Business, Computer, Data Science, Economics, E...",1.0,Entry,"Excel, Python, Reporting, SQL","Attention to Detail, Communication, Creativity...",Two Sigma is a different kind of investment ma...,437,2020
7,Data Analyst,DMGT,New York,Unspecified,"Business, Computer, Data Visualization, Engine...",-1.0,Unspecified,"Airflow, BigQuery, Data Modeling, Data Visuali...","Creativity, Customer Service, Problem Solving,...",The Data Analyst is an integral member of the ...,467,2020
8,"Data Analyst, Merchant Health",Riskified,New York,Master,"AI, Business",1.0,Entry,"Python, R, SQL","Adaptability, Collaboration, Communication, Pr...",About Us\n\nRiskified is the AI platform power...,510,2020
9,Data Analyst,NYU Langone Health,New York,"Bachelor, Master","Biostatistics, Data Management, Data Science, ...",2.0,Entry,"Automation, Data Visualization, R, Reporting, ...","Attention to Detail, Collaboration, Communicat...",NYU Grossman School of Medicine is one of the ...,661,2020
10,Data Analyst,BulbHead,New Jersey,Bachelor,"Business, Computer, Economics, Engineering, Ma...",2.0,Entry,"BigQuery, Data Visualization, Excel, Forecasti...","Adaptability, Analytical Thinking, Collaborati...",BulbHead is currently seeking a Data Analyst t...,801,2020
11,DATA ANALYST,Montefiore Medical,New York,"Bachelor, Master","Business, Data Management",2.0,Entry,Reporting,"Attention to Detail, Collaboration",Job Summary:\n\nThe Clinical Research Data Ana...,437,2020
12,Senior Data Analyst,Known,New York,"Bachelor, Doctorate","Business, Data Science, Financial, Machine Lea...",2.0,Senior,"Automation, Excel, MS Word, Machine Learning, ...","Adaptability, Communication, Initiative, Multi...",About Known\n\nKnown is a modern marketing com...,419,2020
13,Investment Advisory Data Analyst,Advisor Group,New Jersey,"Bachelor, Diploma, Master","Business, Economics, Financial, Physics, Relat...",2.0,Entry,"Excel, Reporting, SQL, SQL Server, VBA",Communication,Investment Advisory Compliance Opportunity in ...,520,2020
14,Sustainability Data Analyst,CodeGreen Solutions,New York,Bachelor,"Data Management, Engineering, Related Field",0.0,Entry,"Excel, Python, R, Reporting, SQL","Attention to Detail, Collaboration, Communicat...",Job Description\nRole Description\n\nSustainab...,326,2020

In [547]:
df_merge.to_csv('data_norm.csv', index=False)

#from google.colab import files
#files.download('data_norm.csv')

**Exploratory Data Analysis (EDA)**

In [548]:
top_state = (
    df_merge.groupby('lokasi')
            .size()
            .reset_index(name='jumlah_lowongan')
            .sort_values(by='jumlah_lowongan', ascending=False)
)

print(top_state)

            lokasi  jumlah_lowongan
24        Missouri             1437
4       California             1092
43           Texas              583
35        Oklahoma              581
15          Kansas              575
31        New York              442
48      Washington              349
3         Arkansas              328
47        Virginia              293
12        Illinois              255
29      New Jersey              234
37    Pennsylvania              230
20   Massachusetts              227
8          Florida              224
32  North Carolina              213
19        Maryland              194
9          Georgia              185
44         Unknown              144
5         Colorado              136
34            Ohio              120
2          Arizona              110
22       Minnesota              101
21        Michigan               75
42       Tennessee               72
13         Indiana               68
49       Wisconsin               58
36          Oregon               45
38          Remote               41
26        Nebraska               36
45            Utah               33
16        Kentucky               33
6      Connecticut               17
40  South Carolina               17
27          Nevada               15
17       Louisiana               13
7         Delaware               13
0          Alabama               12
10          Hawaii               11
30      New Mexico               11
14            Iowa                9
23     Mississippi                6
11           Idaho                5
33    North Dakota                5
39    Rhode Island                4
18           Maine                4
28   New Hampshire                3
25         Montana                3
41    South Dakota                3
1           Alaska                2
50         Wyoming                2
46         Vermont                1

In [549]:
hard = (
    df_merge[['tahun', 'hard_skill']]
    .dropna()
    .assign(hard_skill=lambda x: x['hard_skill'].str.split(','))
    .explode('hard_skill')
)

hard['hard_skill'] = hard['hard_skill'].str.strip()

hard_count = (
    hard.groupby(['tahun', 'hard_skill'])
        .size()
        .reset_index(name='jumlah')
)

hard_count['persentase'] = (
    hard_count['jumlah']
    / hard_count.groupby('tahun')['jumlah'].transform('sum')
    * 100
).round(2)

top10_hard = (
    hard_count.sort_values(
        ['tahun', 'persentase'],
        ascending=[True, False]
    )
    .groupby('tahun')
    .head(5)
)

print(top10_hard)

     tahun          hard_skill  jumlah  persentase
88    2020           Reporting    2944       11.17
92    2020                 SQL    2591        9.83
32    2020               Excel    1864        7.07
108   2020          Statistics    1789        6.79
110   2020             Tableau    1135        4.31
194   2022           Reporting     863        9.65
198   2022                 SQL     627        7.01
212   2022          Statistics     593        6.63
146   2022               Excel     575        6.43
213   2022             Tableau     479        5.35
301   2023           Reporting    1475       12.00
305   2023                 SQL    1123        9.14
319   2023          Statistics     890        7.24
249   2023               Excel     813        6.62
237   2023  Data Visualization     697        5.67
414   2024           Reporting    1157       10.72
418   2024                 SQL     915        8.48
434   2024          Statistics     750        6.95
345   2024  Data Visualization     696        6.45
358   2024               Excel     643        5.96
514   2025                 SQL     158       10.22
510   2025           Reporting     148        9.57
458   2025  Data Visualization     114        7.37
527   2025          Statistics     101        6.53
506   2025              Python      99        6.40

In [550]:
soft = (
    df_merge[['tahun', 'soft_skill']]
    .dropna()
    .assign(soft_skill=lambda x: x['soft_skill'].str.split(','))
    .explode('soft_skill')
)

soft['soft_skill'] = soft['soft_skill'].str.strip()

soft_count = (
    soft.groupby(['tahun', 'soft_skill'])
        .size()
        .reset_index(name='jumlah')
)

soft_count['persentase'] = (
    soft_count['jumlah']
    / soft_count.groupby('tahun')['jumlah'].transform('sum')
    * 100
).round(2)

top10_soft = (
    soft_count.sort_values(
        ['tahun', 'persentase'],
        ascending=[True, False]
    )
    .groupby('tahun')
    .head(5)
)

print(top10_soft)

     tahun           soft_skill  jumlah  persentase
6     2020        Communication    1816       12.48
4     2020  Attention to Detail    1196        8.22
28    2020      Problem Solving     889        6.11
5     2020        Collaboration     835        5.74
19    2020           Leadership     768        5.28
43    2022        Communication     607       11.65
56    2022           Leadership     514        9.86
54    2022           Initiative     429        8.23
51    2022      Decision Making     403        7.73
63    2022  Presentation Skills     392        7.52
80    2023        Communication     738        9.55
93    2023           Leadership     726        9.39
75    2023         Adaptability     666        8.62
100   2023  Presentation Skills     582        7.53
91    2023           Initiative     562        7.27
117   2024        Communication     810       12.32
116   2024        Collaboration     479        7.28
130   2024           Leadership     448        6.81
139   2024      Problem Solving     438        6.66
125   2024      Decision Making     359        5.46
154   2025        Communication      94       11.85
161   2025      Decision Making      64        8.07
153   2025        Collaboration      63        7.94
172   2025      Problem Solving      57        7.19
152   2025  Attention to Detail      50        6.31

In [551]:
edu = (
    df_merge.groupby(['tahun', 'pendidikan'])
            .size()
            .reset_index(name='jumlah')
)

edu['persentase'] = (
    edu['jumlah']
    / edu.groupby('tahun')['jumlah'].transform('sum')
    * 100
).round(2)

edu_unspecified = edu[edu['pendidikan'] == 'Unspecified']

print(edu_unspecified)

     tahun   pendidikan  jumlah  persentase
31    2020  Unspecified     997       24.20
53    2022  Unspecified     137       12.66
75    2023  Unspecified     192       10.87
106   2024  Unspecified     263       17.34
117   2025  Unspecified      40       21.62

In [552]:
level_exp = (
    df_merge.groupby('level')
            .agg(
                jumlah_lowongan=('level','size'),
                rata_pengalaman=('pengalaman','mean')
            )
            .reset_index()
)

level_exp['rata_pengalaman'] = (
    level_exp['rata_pengalaman']
    .round(2)
)

print(level_exp)

         level  jumlah_lowongan  rata_pengalaman
0        Entry             2136             1.12
1   Internship              145            -0.55
2         Lead              520             7.49
3      Manager              114             2.83
4          Mid             1338             3.37
5       Senior             2763             4.11
6  Unspecified             1654            -1.00